import * as Location from 'expo-location'; import { AppError } from '@/lib/errors'; import { supabase } from '@/lib/supabase'; import type { DeliveryJob, JobStatus } from '@/types/domain';
export async function getRiderStatus() { const { data, error } = await supabase.from('riders').select('is_online,verification_status,current_latitude,current_longitude').single(); if (error) throw new AppError('Unable to load rider status.', error); return data as { is_online: boolean; verification_status: string; current_latitude: number | null; current_longitude: number | null }; }
export async function listAvailableJobs(): Promise<DeliveryJob[]> { const { data, error } = await supabase.from('delivery_jobs').select('*, order:orders(*)').eq('status', 'available').order('created_at'); if (error) throw new AppError('Unable to load delivery jobs.', error); return (data ?? []) as DeliveryJob[]; }
export async function listMyJobs(): Promise<DeliveryJob[]> { const { data, error } = await supabase.from('delivery_jobs').select('*, order:orders(*)').neq('status', 'available').order('created_at', { ascending: false }).limit(50); if (error) throw new AppError('Unable to load your jobs.', error); return (data ?? []) as DeliveryJob[]; }
export async function acceptJob(jobId: string) { const { data, error } = await supabase.rpc('accept_delivery_job', { p_job_id: jobId }); if (error) throw new AppError(error.message, error); return data as DeliveryJob; }
export async function updateJob(jobId: string, status: JobStatus) { const { data, error } = await supabase.rpc('transition_delivery_job', { p_job_id: jobId, p_new_status: status }); if (error) throw new AppError(error.message, error); return data as DeliveryJob; }
export async function setAvailability(isOnline: boolean) { const { error } = await supabase.rpc('set_rider_availability', { p_is_online: isOnline }); if (error) throw new AppError('Unable to update availability.', error); }
export async function updateCurrentLocation() { const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) throw new AppError('Location permission is required while you are online.'); const location = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); const { error } = await supabase.rpc('update_rider_location', { p_latitude: location.coords.latitude, p_longitude: location.coords.longitude }); if (error) throw new AppError('Unable to update your location.', error); }
export async function setRiderOnline(isOnline: boolean) { if (!isOnline) return setAvailability(false); const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) throw new AppError('Enable location access in Settings before going online.'); const location = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High }); await setAvailability(true); const { error } = await supabase.rpc('update_rider_location', { p_latitude: location.coords.latitude, p_longitude: location.coords.longitude }); if (error) { await setAvailability(false); throw new AppError('Your location could not be verified, so you remain offline.', error); } }
