export type AppRole = 'customer' | 'rider' | 'laundry_partner' | 'admin';
export type VerificationStatus = 'pending' | 'approved' | 'rejected' | 'suspended';
export type OrderStatus = 'pending' | 'laundry_confirmation' | 'confirmed' | 'searching_pickup_rider' | 'pickup_rider_assigned' | 'rider_to_customer' | 'picked_up' | 'rider_to_laundry' | 'received_by_laundry' | 'processing' | 'ready_for_return' | 'searching_return_rider' | 'return_rider_assigned' | 'out_for_delivery' | 'delivered' | 'completed' | 'cancelled' | 'rejected';
export type JobType = 'pickup_to_laundry' | 'laundry_to_customer';
export type JobStatus = 'available' | 'assigned' | 'accepted' | 'arriving' | 'picked_up' | 'completed' | 'cancelled';
export type PricingType = 'per_kg' | 'fixed';
export interface Profile { id: string; role: AppRole; full_name: string; phone: string | null; avatar_url: string | null; status: VerificationStatus; created_at: string; updated_at: string }
export interface Address { id: string; user_id: string; label: string; full_address: string; barangay: string; city: string; province: string; latitude: number | string; longitude: number | string; is_default: boolean; created_at: string }
export interface LaundryService { id: string; shop_id: string; name: string; description: string | null; price: number | string; pricing_type: PricingType; minimum_charge: number | string; estimated_turnaround_hours: number; is_active: boolean }
export interface LaundryShop { id: string; owner_id: string; name: string; description: string | null; logo_url: string | null; phone: string; address: string; city: string; province: string; latitude: number | string; longitude: number | string; is_verified: boolean; is_active: boolean; average_rating: number | string; operating_hours: Record<string, unknown>; services?: LaundryService[]; service_zone_id?: string | null }
export interface OrderItem { id: string; order_id: string; service_id: string; quantity: number | string; unit_price: number | string; subtotal: number | string; service?: LaundryService }
export interface Order { id: string; order_number: string; customer_id: string; laundry_shop_id: string; pickup_address_id: string; service_zone_id?: string | null; pickup_date: string; pickup_time: string; status: OrderStatus; estimated_weight: number | string; laundry_subtotal: number | string; pickup_delivery_fee: number | string; return_delivery_fee: number | string; platform_fee: number | string; total_amount: number | string; amount_due: number | string; amount_paid: number | string; remaining_balance: number | string; payment_method: 'cod' | 'pay_later'; payment_status: 'unpaid' | 'partial' | 'paid' | 'refunded'; special_instructions: string | null; created_at: string; updated_at: string; completed_at: string | null; laundry_shop?: LaundryShop; pickup_address?: Address; order_items?: OrderItem[] }
export interface DeliveryJob { id: string; order_id: string; type: JobType; rider_id: string | null; pickup_latitude: number | string; pickup_longitude: number | string; destination_latitude: number | string; destination_longitude: number | string; status: JobStatus; rider_payout: number | string; created_at: string; order?: Order }
export interface DeliveryProof { id: string; proof_type: string; photo_path: string; latitude: number | string; longitude: number | string; created_at: string }
export interface DashboardMetric { label: string; value: string | number; hint?: string }
