export type AppRole = 'customer' | 'rider' | 'laundry_partner' | 'admin';
export type VerificationStatus = 'pending' | 'approved' | 'rejected' | 'suspended';
export type OrderStatus = 'pending' | 'laundry_confirmation' | 'confirmed' | 'searching_pickup_rider' | 'pickup_rider_assigned' | 'rider_to_customer' | 'picked_up' | 'rider_to_laundry' | 'received_by_laundry' | 'processing' | 'ready_for_return' | 'searching_return_rider' | 'return_rider_assigned' | 'out_for_delivery' | 'delivered' | 'completed' | 'cancelled' | 'rejected';
export type JobType = 'pickup_to_laundry' | 'laundry_to_customer';
export type JobStatus = 'available' | 'assigned' | 'accepted' | 'arriving' | 'picked_up' | 'completed' | 'cancelled';
export type PricingType = 'per_kg' | 'fixed';
export interface Profile { id: string; role: AppRole; full_name: string; phone: string | null; avatar_url: string | null; status: VerificationStatus; created_at: string; updated_at: string }
export interface Address { id: string; user_id: string; label: string; full_address: string; barangay: string; city: string; province: string; latitude: number; longitude: number; is_default: boolean }
export interface LaundryService { id: string; shop_id: string; name: string; description: string | null; price: number; pricing_type: PricingType; minimum_charge: number; estimated_turnaround_hours: number; is_active: boolean }
export interface LaundryShop { id: string; owner_id: string; name: string; description: string | null; logo_url: string | null; phone: string; address: string; city: string; province: string; latitude: number; longitude: number; is_verified: boolean; is_active: boolean; average_rating: number; operating_hours: Record<string, unknown>; services?: LaundryService[] }
export interface OrderItem { id: string; order_id: string; service_id: string; quantity: number; unit_price: number; subtotal: number; service?: LaundryService }
export interface Order { id: string; order_number: string; customer_id: string; laundry_shop_id: string; pickup_address_id: string; pickup_date: string; pickup_time: string; status: OrderStatus; estimated_weight: number; laundry_subtotal: number; pickup_delivery_fee: number; return_delivery_fee: number; platform_fee: number; total_amount: number; amount_due: number; amount_paid: number; remaining_balance: number; payment_method: 'cod' | 'pay_later'; payment_status: 'unpaid' | 'partial' | 'paid' | 'refunded'; special_instructions: string | null; created_at: string; updated_at: string; completed_at: string | null; laundry_shop?: LaundryShop; pickup_address?: Address; order_items?: OrderItem[] }
export interface DeliveryJob { id: string; order_id: string; type: JobType; rider_id: string | null; pickup_latitude: number; pickup_longitude: number; destination_latitude: number; destination_longitude: number; status: JobStatus; rider_payout: number; created_at: string; order?: Order }
export interface DashboardMetric { label: string; value: string | number; hint?: string }
