alter table public.profiles enable row level security; alter table public.addresses enable row level security; alter table public.service_zones enable row level security; alter table public.laundry_shops enable row level security; alter table public.laundry_services enable row level security; alter table public.riders enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.order_status_logs enable row level security; alter table public.delivery_jobs enable row level security; alter table public.delivery_proofs enable row level security; alter table public.payments enable row level security; alter table public.ratings enable row level security; alter table public.notifications enable row level security; alter table public.push_tokens enable row level security; alter table public.chat_rooms enable row level security; alter table public.messages enable row level security;

create policy profiles_select on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
create policy profiles_update_self on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid() and role=(select p.role from public.profiles p where p.id=auth.uid()) and status=(select p.status from public.profiles p where p.id=auth.uid()));
create policy addresses_owner_all on public.addresses for all to authenticated using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy zones_read on public.service_zones for select to authenticated using(is_active or public.is_admin()); create policy zones_admin on public.service_zones for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy shops_discovery on public.laundry_shops for select to authenticated using((is_verified and is_active) or owner_id=auth.uid() or public.is_admin()); create policy shops_owner_update on public.laundry_shops for update to authenticated using(owner_id=auth.uid() or public.is_admin()) with check(owner_id=auth.uid() or public.is_admin());
create policy services_read on public.laundry_services for select to authenticated using(exists(select 1 from public.laundry_shops s where s.id=shop_id and ((s.is_verified and s.is_active) or s.owner_id=auth.uid() or public.is_admin()))); create policy services_owner_all on public.laundry_services for all to authenticated using(exists(select 1 from public.laundry_shops s where s.id=shop_id and (s.owner_id=auth.uid() or public.is_admin()))) with check(exists(select 1 from public.laundry_shops s where s.id=shop_id and (s.owner_id=auth.uid() or public.is_admin())));
create policy riders_self_select on public.riders for select to authenticated using(profile_id=auth.uid() or public.is_admin() or exists(select 1 from public.delivery_jobs j join public.orders o on o.id=j.order_id where j.rider_id=riders.id and o.customer_id=auth.uid()));
create policy orders_participant_select on public.orders for select to authenticated using(customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=laundry_shop_id and s.owner_id=auth.uid()) or exists(select 1 from public.delivery_jobs j join public.riders r on r.id=j.rider_id where j.order_id=orders.id and r.profile_id=auth.uid()) or public.is_admin());
create policy order_items_participant on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()) or exists(select 1 from public.delivery_jobs j join public.riders r on r.id=j.rider_id where j.order_id=o.id and r.profile_id=auth.uid()) or public.is_admin())));
create policy logs_participant on public.order_status_logs for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()) or exists(select 1 from public.delivery_jobs j join public.riders r on r.id=j.rider_id where j.order_id=o.id and r.profile_id=auth.uid()) or public.is_admin())));
create policy jobs_eligible_select on public.delivery_jobs for select to authenticated using(public.is_admin() or exists(select 1 from public.riders r where r.profile_id=auth.uid() and r.verification_status='approved' and (r.id=rider_id or (r.is_online and status='available' and r.service_zone_id=(select o.service_zone_id from public.orders o where o.id=order_id)))) or exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()))));
create policy proofs_participant_select on public.delivery_proofs for select to authenticated using(public.is_admin() or exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()))) or captured_by=auth.uid());
create policy proofs_rider_insert on public.delivery_proofs for insert to authenticated with check(captured_by=auth.uid() and exists(select 1 from public.delivery_jobs j join public.riders r on r.id=j.rider_id where j.id=delivery_job_id and j.order_id=order_id and r.profile_id=auth.uid()));
create policy payments_participant on public.payments for select to authenticated using(public.is_admin() or exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()))));
create policy ratings_read on public.ratings for select to authenticated using(true); create policy ratings_customer_insert on public.ratings for insert to authenticated with check(customer_id=auth.uid() and exists(select 1 from public.orders o where o.id=order_id and o.customer_id=auth.uid() and o.status='completed'));
create policy notifications_owner on public.notifications for select to authenticated using(user_id=auth.uid() or public.is_admin()); create policy notifications_owner_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy tokens_owner on public.push_tokens for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy chats_participant on public.chat_rooms for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()) or exists(select 1 from public.delivery_jobs j join public.riders r on r.id=j.rider_id where j.order_id=o.id and r.profile_id=auth.uid()) or public.is_admin())));
create policy messages_participant_select on public.messages for select to authenticated using(exists(select 1 from public.chat_rooms c join public.orders o on o.id=c.order_id where c.id=room_id and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()) or exists(select 1 from public.delivery_jobs j join public.riders r on r.id=j.rider_id where j.order_id=o.id and r.profile_id=auth.uid()) or public.is_admin()))); create policy messages_participant_insert on public.messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.chat_rooms c join public.orders o on o.id=c.order_id where c.id=room_id and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()) or exists(select 1 from public.delivery_jobs j join public.riders r on r.id=j.rider_id where j.order_id=o.id and r.profile_id=auth.uid()) or public.is_admin())));

insert into storage.buckets(id,name,public) values('avatars','avatars',true),('laundry-logos','laundry-logos',true),('delivery-proofs','delivery-proofs',false),('verification-documents','verification-documents',false) on conflict(id) do nothing;
create policy avatar_public_read on storage.objects for select using(bucket_id in ('avatars','laundry-logos')); create policy avatar_owner_write on storage.objects for insert to authenticated with check(bucket_id in ('avatars','laundry-logos') and (storage.foldername(name))[1]=auth.uid()::text);
create policy proof_participant_read on storage.objects for select to authenticated using(bucket_id='delivery-proofs' and exists(select 1 from public.orders o where o.id::text=(storage.foldername(name))[1] and (o.customer_id=auth.uid() or exists(select 1 from public.laundry_shops s where s.id=o.laundry_shop_id and s.owner_id=auth.uid()) or exists(select 1 from public.delivery_jobs j join public.riders r on r.id=j.rider_id where j.order_id=o.id and r.profile_id=auth.uid()) or public.is_admin())));
create policy proof_rider_write on storage.objects for insert to authenticated with check(bucket_id='delivery-proofs' and exists(select 1 from public.riders r where r.profile_id=auth.uid() and r.verification_status='approved'));
create policy verification_owner_write on storage.objects for insert to authenticated with check(bucket_id='verification-documents' and (storage.foldername(name))[1]=auth.uid()::text); create policy verification_admin_read on storage.objects for select to authenticated using(bucket_id='verification-documents' and public.is_admin());

alter publication supabase_realtime add table public.orders,public.order_status_logs,public.delivery_jobs,public.notifications,public.riders;
